#pragma once
#include <hdf5.h>
hid_t shim_H5T_NATIVE_UCHAR(void);
hid_t shim_H5T_NATIVE_USHORT(void);
hid_t shim_H5T_NATIVE_INT(void);
hid_t shim_H5T_NATIVE_LLONG(void);
hid_t shim_H5T_IEEE_F64LE(void);
hid_t shim_H5T_C_S1(void);
hid_t shim_H5P_LINK_CREATE(void);
